### ISSUE TITLE
10.0, 11.0 and 12.0: odoo/src does not exists

### ISSUE THREAD

**Issue by rvalyi** [akretion/docky-odoo-template#2]
in fact with such odoo/spec.yaml, odoo is donwloaded in odoo/external-src/odoo not odoo/src. Then the ```docky build``` command fail with the following error:

```
Removing intermediate container d76ad18b8291
Step 6/10 : RUN pip install -e /odoo/src
 ---> Running in 27128617f156
/odoo/src should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+
ERROR: Service 'odoo' failed to build: The command '/bin/sh -c pip install -e /odoo/src' returned a non-zero code: 1
Traceback (most recent call last):
  File "/usr/local/bin/docky", line 11, in <module>
    load_entry_point('docky==4.0.4', 'console_scripts', 'docky')()
  File "/usr/local/lib/python2.7/dist-packages/docky/main.py", line 7, in main
    Docky.run()
  File "/usr/local/lib/python2.7/dist-packages/plumbum/cli/application.py", line 485, in run
    inst, retcode = subapp.run(argv, exit = False)
  File "/usr/local/lib/python2.7/dist-packages/plumbum/cli/application.py", line 480, in run
    retcode = inst.main(*tailargs)
  File "/usr/local/lib/python2.7/dist-packages/docky/cmd/base.py", line 99, in main
    self._main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docky/cmd/forward.py", line 13, in _main
    return self._run(self.compose[self._cmd.split(' ')])
  File "/usr/local/lib/python2.7/dist-packages/docky/cmd/base.py", line 96, in _run
    self.parent._run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docky/cmd/base.py", line 39, in _run
    return cmd & retcode
  File "/usr/local/lib/python2.7/dist-packages/plumbum/commands/modifiers.py", line 144, in __rand__
    cmd(retcode = self.retcode, stdin = None, stdout = None, stderr = None)
  File "/usr/local/lib/python2.7/dist-packages/plumbum/commands/base.py", line 90, in __call__
    return self.run(args, **kwargs)[1]
  File "/usr/local/lib/python2.7/dist-packages/plumbum/commands/base.py", line 220, in run
    return p.run()
  File "/usr/local/lib/python2.7/dist-packages/plumbum/commands/base.py", line 182, in runner
    return run_proc(p, retcode, timeout)
  File "/usr/local/lib/python2.7/dist-packages/plumbum/commands/processes.py", line 206, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/usr/local/lib/python2.7/dist-packages/plumbum/commands/processes.py", line 23, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/usr/local/lib/python2.7/dist-packages/plumbum/machines/base.py", line 22, in verify
    stdout, stderr)
plumbum.commands.processes.ProcessExecutionError: Command line: ['/usr/local/bin/docker-compose', '-f', 'dev.docker-compose.yml', '--project-name', 'rvalyi_docky12-2', 'build']
Exit code: 1
```

workaround: move odoo/external-src/odoo to odoo/src before running docky build. A better solution is needed though. As far as I can see, in the docker-odoo-shopinvader template, a mysterious pre-existing src folder is copied to odoo/src at the beginning of the Dockerfile. Not sure how we are supposed to provision that previous src folder though: https://github.com/akretion/docker-odoo-shopinvader/blob/10.0/odoo/Dockerfile#L6

cc @clementmbr @sebastienbeau

**Comment by EBII** [comment]
Je crois que c'est la commande ak build dans le dossier odoo qui lit spec.yaml pour génerer le fichier repo.yaml et fait tourner git-aggregator.

**Comment by rvalyi** [comment]
fixed these days
