### ISSUE TITLE
.env creation instruction is not clear

### ISSUE THREAD

**Issue by rvalyi** [akretion/docky-odoo-template#61]
in the readme it says create a .env file without any further detail.

problem is a dump user might do something like touch .env
and then when trying to run docky run have a cryptic error like:

```
rvalyi@rvalyi-laptop:~/DEV/odoo16$ docky run
/usr/lib/python3/dist-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
The ENCRYPTION_KEY_DEV variable is not set. Defaulting to a blank string.
The ENCRYPTION_KEY_PROD variable is not set. Defaulting to a blank string.
The ENCRYPTION_KEY_PREPROD variable is not set. Defaulting to a blank string.
The UID variable is not set. Defaulting to a blank string.
The ENV variable is not set. Defaulting to a blank string.
The COMPOSE_PROJECT_NAME variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "/usr/local/bin/docky", line 33, in <module>
    sys.exit(load_entry_point('docky', 'console_scripts', 'docky')())
  File "/home/rvalyi/DEV/src/docky/docky/main.py", line 7, in main
    Docky.run()
  File "/home/rvalyi/.local/lib/python3.10/site-packages/plumbum/cli/application.py", line 629, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/rvalyi/.local/lib/python3.10/site-packages/plumbum/cli/application.py", line 624, in run
    retcode = inst.main(*tailargs)
  File "/home/rvalyi/DEV/src/docky/docky/cmd/base.py", line 53, in main
    self._init_project()
  File "/home/rvalyi/DEV/src/docky/docky/cmd/base.py", line 48, in _init_project
    self.project = Project()
  File "/home/rvalyi/DEV/src/docky/docky/common/project.py", line 19, in __init__
    self.project = command.project_from_options('.', {})
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 148, in get_project
    config_data = config.load(config_details, interpolate)
  File "/usr/lib/python3/dist-packages/compose/config/config.py", line 442, in load
    service_dicts = load_services(config_details, main_file, interpolate=interpolate)
  File "/usr/lib/python3/dist-packages/compose/config/config.py", line 558, in load_services
    return build_services(service_config)
  File "/usr/lib/python3/dist-packages/compose/config/config.py", line 537, in build_services
    return sort_service_dicts([
  File "/usr/lib/python3/dist-packages/compose/config/config.py", line 538, in <listcomp>
    build_service(name, service_dict, service_names)
  File "/usr/lib/python3/dist-packages/compose/config/config.py", line 525, in build_service
    validate_service(service_config, service_names, config_file)
  File "/usr/lib/python3/dist-packages/compose/config/config.py", line 781, in validate_service
    validate_service_constraints(service_dict, service_name, config_file)
  File "/usr/lib/python3/dist-packages/compose/config/validation.py", line 487, in validate_service_constraints
    handle_errors(validator.iter_errors(config), handler, None)
  File "/usr/lib/python3/dist-packages/compose/config/validation.py", line 542, in handle_errors
    raise ConfigurationError(
compose.config.errors.ConfigurationError: The Compose file is invalid because:
Service odoo has neither an image nor a build context specified. At least one must be provided.
```

how can we be more explicit. Here is my basic .env file to get it working:
```
ENV=dev
COMPOSE_FILE=docker-compose.yml:dev.docker-compose.yml
COMPOSE_PROJECT_NAME=odoo16
DOCKER_BUILDKIT=1
COMPOSE_DOCKER_CLI_BUILD=1
```

**Comment by rvalyi** [comment]
in fact the `env-sample.jinja` instruction is present in  the README, so closing
