### ISSUE TITLE
missing odoo/external-src

### ISSUE THREAD

**Issue by rvalyi** [akretion/docky-odoo-template#9]
Doesn't seem trivial to add as odoo/external-src is in .gitignore

```
Step 7/14 : COPY ./external-src /odoo/external-src
ERROR: Service 'odoo' failed to build : lstat external-src: no such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/docky", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/docky/main.py", line 7, in main
    Docky.run()
  File "/usr/local/lib/python3.8/dist-packages/plumbum/cli/application.py", line 577, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/usr/local/lib/python3.8/dist-packages/plumbum/cli/application.py", line 572, in run
    retcode = inst.main(*tailargs)
  File "/usr/local/lib/python3.8/dist-packages/docky/cmd/base.py", line 54, in main
    self._main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/docky/cmd/forward.py", line 16, in _main
    return self._run(self.compose[cmd])
  File "/usr/local/lib/python3.8/dist-packages/docky/cmd/base.py", line 45, in _run
    self.parent._run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/docky/cmd/base.py", line 24, in _run
    return cmd & retcode
  File "/usr/local/lib/python3.8/dist-packages/plumbum/commands/modifiers.py", line 150, in __rand__
    cmd(retcode=self.retcode,
  File "/usr/local/lib/python3.8/dist-packages/plumbum/commands/base.py", line 96, in __call__
    return self.run(args, **kwargs)[1]
  File "/usr/local/lib/python3.8/dist-packages/plumbum/commands/base.py", line 232, in run
    return p.run()
  File "/usr/local/lib/python3.8/dist-packages/plumbum/commands/base.py", line 193, in runner
    return run_proc(p, retcode, timeout)
  File "/usr/local/lib/python3.8/dist-packages/plumbum/commands/processes.py", line 302, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/usr/local/lib/python3.8/dist-packages/plumbum/commands/processes.py", line 22, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/usr/local/lib/python3.8/dist-packages/plumbum/machines/base.py", line 24, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | /usr/local/bin/docker-compose build
```

**Comment by rvalyi** [comment]
odoo/links is missing too
